### ISSUE TITLE
Support for ActiveJob

### ISSUE THREAD

**Issue by seanhandley** [fastly/sidekiq-prometheus#16]
I have a use-case for prometheus metrics from ActiveJob via sidekiq.

It seems if I define a job class by mixing in `Sidekiq::Worker` then I see prometheus metrics. However, most Rails jobs are defined by inheriting from the `ActiveJob::Base` class and it seems metrics are not collected by default for this.

Have I missed something?

**Comment by mirubiri** [comment]
@seanhandley [Add ActiveJob Support](https://github.com/fastly/sidekiq-prometheus/pull/19)  🎁

**Comment by leklund** [comment]
Resolved by #22 and released in [1.3.0](https://github.com/fastly/sidekiq-prometheus/releases/tag/v1.3.0)
