### ISSUE TITLE
Suspected bug in reporting `sidekiq_retry_size` after leader changeover.

### ISSUE THREAD

**Issue by leehambley** [fastly/sidekiq-prometheus#24]
Please see the attached screenshot which shows 10 days of our ~30-45 node (elastic) Sidekiq cluster.

We're running a bit older versions of Sidekiq(enterprise):

```
gem "sidekiq", "~> 5.1.3"
gem "sidekiq-ent", "~> 1.6.1", source: SIDEKIQENT_GEM
gem "sidekiq-failures", "1.0.0"
gem "sidekiq_prometheus", "1.4.0"
```

What we believe happened here is that the instance in sour green color continued reporting cached or stale results even after the ever growing (we have an amplification bug in a certain class of jobs...) retries queue. 

Mistakenly our Graph was configured to show `max(sidekiq_retry_size)`, which meant that our monitoring did not reflect the return to a healthy state after we manually truncated the retries queue using the sidekiq dashboard.

Unfortuantely we lost access to these instances in a downscaling event before we could do more forensics, but we suspect something like the node using SidekiqPrometheus, but no longer elected as leader, continues to report metrics, but is somehow not refreshing the underlying data, because this instance is not the leader.

As a workaround we are seeking to do some kind of label inflection to detect the youngest unique `instance` label value, and select only series with this label.

![image](https://user-images.githubusercontent.com/18952/124726065-ba69d900-df0d-11eb-9e1f-5a59a47d7b2a.png)

**Comment by leklund** [comment]
Fixed by #36
