### ISSUE TITLE
Registry reports outdated metrics for Sidekiq worker that is no longer a leader

### ISSUE THREAD

**Issue by hiddewie** [fastly/sidekiq-prometheus#35]
Registering and reporting global Sidekiq metrics is conditional on the process being the Sidekiq leader. This is a good thing.

However, the metrics are not unregistered if the Sidekiq worker is no longer the leader, which means that the registry will keep polling and outputting the outdated metrics. The metrics will not be updated because the Sidekiq worker is no longer the leader.

Below is an example metrics query of `avg without (job) (sidekiq_enqueued{queue="pre_create_all_events"})`: 
![image](https://user-images.githubusercontent.com/1073881/215102805-f25e4dc3-83a2-4a3a-b763-f00b5acbf99f.png)

Note that certain lines continue without meaningful data, while Sidekiq processes that become the new leader do report up-to-date metrics.

**Comment by leklund** [comment]
Thanks for reporting this bug! Seems like this is the same issue as #24 -- The correct behavior is probably to unresigter the metrics if an instance has been demoted.
